# Matrixes
The size of a matrix is described by numbers of rows and columns.
> A = (rows x columns)

Hence, when calling a cell in matrix, the first variable corresponds to the row, and the second one - column.

     [a11, a12, a13, ..., a1n]
     [a21, a22, a23, ..., a2n]
     [...  ...  ...  ...  ...]
     [am1, am2, am3, ..., amn]
    
Matrix can be multiplied by a vector, provided that the number of columns in matrix and the length of a vector are the same.

## Multiplying matrix by vector:

In [42]:
import numpy as np

In [49]:
matrix = np.array([
    [1, 2, 3, 4, 5],
    [0, 2, 1, 3, 4],
    [4, 3, 1, 0, 3]
    ])
vector = np.array([1, 2, 3, 4, 5])
count = 0
outcome = []

for row in range(len(matrix)):
    for column in range(len(matrix[row])):
        matrix[row][column] = matrix[row][column] * vector[column]
        count += matrix[row][column]
    outcome.append(count)
    count = 0
    
print(f"Multiplied matrix: \n{matrix}\n")
print(f"Resulting vector: \n{outcome}")

Multiplied matrix: 
[[ 1  4  9 16 25]
 [ 0  4  3 12 20]
 [ 4  6  3  0 15]]

Resulting vector: 
[55, 39, 28]


## Multipliyng matrix by vector - as a defined funcion:

In [47]:
def matrix_times_vector(matrix, vector):
    count = 0
    outcome = []
    for row in range(len(matrix)):
        for column in range(len(matrix[row])):
            matrix[row][column] = matrix[row][column] * vector[column]
            count += matrix[row][column]
        outcome.append(count)
        count = 0
    return outcome


m = np.array([
    [1, 2, 3, 4, 5],
    [0, 2, 1, 3, 4],
    [4, 3, 1, 0, 3]
    ])

v = np.array([1, 2, 3, 4, 5, 6])

matrix_times_vector(m, v)

[55, 39, 28]

## What if the number of columns and the length of a vector doesnt match?

In [56]:
def matrix_times_vector(matrix, vector):
    count = 0
    outcome = []
    if len(matrix[0]) == len(vector):

        for row in range(len(matrix)):
            for column in range(len(matrix[row])):
                matrix[row][column] = matrix[row][column] * vector[column]
                count += matrix[row][column]
            outcome.append(count)
            count = 0
    else:
       print("Number of items in vector must be the same as number of columns in matrix.")     
    return outcome


m = np.array([
    [1, 2, 3, 4, 5],
    [0, 2, 1, 3, 4],
    [4, 3, 1, 0, 3]
    ])

v = np.array([1, 2, 3, 4, 5])

matrix_times_vector(m, v)

[55, 39, 28]